### ISSUE TITLE
slack not working?

### ISSUE THREAD

**Issue by franfram** [nyhackr/nyhackr#13]
Hello, 

I'm trying to join the myhackr slack using the link provided in the website (https://nyhackr.org/slack.html) but it doesn't seem to work.

**Comment by joemarlo** [comment]
Try this link here: https://join.slack.com/t/nyhackr/shared_invite/zt-z14v6jw3-MIKDmEVqx~SGvn7OTRyPpg

We just redid the website so there might be a few dead links laying around

**Comment by joemarlo** [comment]
Old link now redirects with #15
